batch_size: 64
checkpoint_dir: null
data_dir: data/reach_target/
episodes_per_update: 10
eval: false
eval_batch_size: 10
eval_interval: 10
hidden_dims:
- 64
- 64
- 64
log_dir: logs/rt_mlp_full_ee_64x3/seed53_Apr04_15-39-51
max_episode_length: 100
model_name: mlp
num_epochs: 1000
resume: ''
seed: 53
sub_epochs: 10
tag: full_ee_64x3
