batch_size: 64
checkpoint_dir: null
data_dir: data/reach_target/
episodes_per_update: 20
eval: false
eval_batch_size: 10
eval_interval: 10
hidden_dims:
- 64
- 64
log_dir: logs/rt_mlp_data/seed0_Apr02_17-46-48
max_episode_length: 100
model_name: mlp
num_epochs: 1000
resume: ''
seed: 0
sub_epochs: 5
tag: data
