batch_size: 64
checkpoint_dir: null
data_dir: data/pick_and_lift/
episodes_per_update: 10
eval: false
eval_batch_size: 10
eval_interval: 10
hidden_dims:
- 64
- 64
- 64
log_dir: logs/pl_mlp_ee_64x3/seed53_Apr04_16-56-36
max_episode_length: 100
model_name: mlp
num_epochs: 1000
resume: ''
seed: 53
sub_epochs: 10
tag: ee_64x3
